name: pulse_feed
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  flutter_screenutil: ^5.9.3
  get_it: ^9.2.0
  get: ^4.7.3
  equatable: ^2.0.8
  path_provider: ^2.1.5

  # Local plugins
  pulse_audio_player:
    path: /Users/ibrahimmohammed/StudioProjects/pulse_feed/pulse_audio_player
  pulse_video_player:
    path: /Users/ibrahimmohammed/StudioProjects/pulse_feed/pulse_video_player
  pulse_document_viewer:
    path: /Users/ibrahimmohammed/StudioProjects/pulse_feed/pulse_document_viewer
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true